# Generated by Django 4.2.5 on 2023-09-13 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="senstive",
            new_name="sensitive",
        ),
    ]
