# Generated by Django 4.2.5 on 2023-10-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_rename_senstive_post_sensitive"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoConUS23Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.TextField()),
                ("account", models.JSONField()),
                ("instance", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("in_reply_to_id", models.TextField(blank=True, null=True)),
                ("in_reply_to_account_id", models.TextField(blank=True, null=True)),
                ("sensitive", models.BooleanField(blank=True, null=True)),
                ("spoiler_text", models.TextField(blank=True, null=True)),
                ("visibility", models.TextField()),
                ("language", models.TextField(blank=True, null=True)),
                ("uri", models.URLField()),
                ("url", models.URLField()),
                ("replies_count", models.IntegerField()),
                ("reblogs_count", models.IntegerField()),
                ("favourites_count", models.IntegerField()),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField()),
                ("reblog", models.TextField(blank=True, null=True)),
                ("application", models.JSONField(blank=True, null=True)),
                ("media_attachments", models.JSONField(default=list)),
                ("mentions", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                ("emojis", models.JSONField(default=list)),
                ("card", models.JSONField(blank=True, null=True)),
                ("poll", models.JSONField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("post_id", "instance")},
            },
        ),
    ]
