# Generated by Django 4.2.5 on 2023-10-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_djangoconus23post"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["created_at"], name="posts_post_created_dadbfe_idx"),
        ),
    ]
