# Generated by Django 4.2.5 on 2023-10-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_post_posts_post_created_dadbfe_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("framework_or_lang", models.TextField(blank=True, null=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
