# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
   - id: trailing-whitespace
   - id: end-of-file-fixer
   - id: check-yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.10
  hooks:
   - id: ruff
   - id: ruff-format
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.36.4
  hooks:
   - id: djlint-reformat-django
   - id: djlint-django
ci:
  autoupdate_schedule: 'quarterly' # updates are managed by renovate
