# Generated by Django 4.2.5 on 2023-09-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Daily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_accounts", models.IntegerField()),
                ("python_accounts", models.IntegerField()),
                ("javascript_accounts", models.IntegerField()),
                ("rust_accounts", models.IntegerField()),
                ("ruby_accounts", models.IntegerField()),
                ("golang_accounts", models.IntegerField()),
                ("java_accounts", models.IntegerField()),
                ("kotlin_accounts", models.IntegerField()),
                ("scala_accounts", models.IntegerField()),
                ("swift_accounts", models.IntegerField()),
                ("csharp_accounts", models.IntegerField()),
                ("fsharp_accounts", models.IntegerField()),
                ("dotnet_accounts", models.IntegerField()),
                ("cpp_accounts", models.IntegerField()),
                ("linux_accounts", models.IntegerField()),
                ("haskell_accounts", models.IntegerField()),
                ("ocaml_accounts", models.IntegerField()),
                ("nix_accounts", models.IntegerField()),
                ("opensource_accounts", models.IntegerField()),
                ("php_accounts", models.IntegerField()),
            ],
        ),
    ]
