# Generated by Django 5.0.3 on 2024-03-06 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_accountlookup_language"),
        ("stats", "0003_daily_angular_accounts_daily_angular_posts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("followers_count", models.IntegerField(default=0)),
                ("following_count", models.IntegerField(default=0)),
                ("statuses_count", models.IntegerField(default=0)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.account")),
            ],
        ),
    ]
