# Generated by Django 5.0.3 on 2024-03-08 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_accountlookup_language"),
        ("stats", "0005_rename_accountstats_dailyaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAccountChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("statuses_count", models.IntegerField(default=0)),
                ("followers_count", models.IntegerField(default=0)),
                ("following_count", models.IntegerField(default=0)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.account")),
            ],
        ),
    ]
