# Generated by Django 5.0.3 on 2024-03-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0006_dailyaccountchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="daily",
            name="kubernetes_accounts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="daily",
            name="kubernetes_posts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="daily",
            name="typescript_accounts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="daily",
            name="typescript_posts",
            field=models.IntegerField(default=0),
        ),
    ]
