# Generated by Django 5.0.4 on 2024-05-18 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0011_daily_r_accounts_daily_r_posts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="daily",
            old_name="r_accounts",
            new_name="rstats_accounts",
        ),
        migrations.RenameField(
            model_name="daily",
            old_name="r_posts",
            new_name="rstats_posts",
        ),
    ]
