# Generated by Django 5.1a1 on 2024-06-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0012_rename_r_accounts_daily_rstats_accounts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="daily",
            name="opentofu_accounts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="daily",
            name="opentofu_posts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="daily",
            name="terraform_accounts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="daily",
            name="terraform_posts",
            field=models.IntegerField(default=0),
        ),
    ]
