# Generated by Django 5.1.1 on 2024-10-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0017_remove_monthlyaccountchange_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="daily",
            name="security_accounts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="daily",
            name="security_posts",
            field=models.IntegerField(default=0),
        ),
    ]
