# Generated by Django 5.1.3 on 2024-12-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0020_daily_machinelearning_accounts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="daily",
            name="odin_accounts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="daily",
            name="odin_posts",
            field=models.IntegerField(default=0),
        ),
    ]
