# Generated by Django 5.0.3 on 2024-04-03 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_alter_accountlookup_language"),
        ("mastodon_auth", "0002_accountaccess_delete_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountFollowing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.account")),
            ],
        ),
    ]
