# Generated by Django 5.0.3 on 2024-04-05 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mastodon_auth", "0004_alter_accountfollowing_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instance",
            options={"verbose_name": "Auth Instance", "verbose_name_plural": "Auth Instance"},
        ),
    ]
