# Generated by Django 5.1a1 on 2024-06-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mastodon_auth", "0005_alter_instance_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="scopes",
            field=models.JSONField(
                default=[
                    "read:accounts",
                    "read:blocks",
                    "read:favourites",
                    "read:filters",
                    "read:follows",
                    "read:lists",
                    "read:mutes",
                    "read:notifications",
                    "read:search",
                    "read:statuses",
                    "read:bookmarks",
                    "write:accounts",
                    "write:blocks",
                    "write:favourites",
                    "write:filters",
                    "write:follows",
                    "write:lists",
                    "write:media",
                    "write:mutes",
                    "write:notifications",
                    "write:reports",
                    "write:statuses",
                    "write:bookmarks",
                ]
            ),
        ),
    ]
