# Generated by Django 5.1.5 on 2025-01-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mastodon_auth", "0005_alter_instance_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountfollowing",
            name="url",
            field=models.TextField(),
        ),
    ]
