# Generated by Django 6.1.dev20260604233057 on 2026-06-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mastodon_auth", "0006_alter_accountfollowing_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="scopes",
            field=models.CharField(default="", max_length=255),
        ),
    ]
