# Generated by Django 6.1.dev20260605090940 on 2026-06-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mastodon_auth", "0007_instance_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="software",
            field=models.CharField(default="", max_length=64),
        ),
    ]
