# Generated by Django 6.1.dev20260624094157 on 2026-06-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mastodon_auth", "0008_instance_software"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountaccess",
            name="access_token",
            field=models.TextField(),
        ),
    ]
