# Generated by Django 4.1.7 on 2023-02-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="last_status_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
