# Generated by Django 4.1.7 on 2023-02-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_account_last_status_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="noindex",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
