# Generated by Django 4.1.7 on 2023-03-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_accountlookup"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="accountlookup",
            index=models.Index(
                fields=["language"], name="accounts_ac_languag_951751_idx"
            ),
        ),
    ]
