# Generated by Django 4.2 on 2023-05-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_accountlookupany_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="followers_count",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_status_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="statuses_count",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="url",
            field=models.URLField(db_index=True),
        ),
        migrations.AlterField(
            model_name="accountlookup",
            name="language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("rust", "Rust"),
                    ("ruby", "Ruby"),
                    ("java", "Java"),
                    ("csharp", "C#"),
                    ("kotlin", "Kotlin"),
                    ("fsharp", "F#"),
                    ("scala", "Scala"),
                    ("golang", "Golang"),
                    ("php", "PHP"),
                    ("linux", "Linux"),
                    ("haskell", "Haskell"),
                    ("nix", "Nix"),
                    ("opensource", "Open Source"),
                    ("gaming", "Gaming"),
                    ("security", "Security"),
                ],
                max_length=55,
            ),
        ),
    ]
