# Generated by Django 4.2 on 2023-05-12 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_account_followers_count_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccountLookupAny",
        ),
    ]
