# Generated by Django 4.2 on 2023-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_delete_accountlookupany"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="instance",
            field=models.TextField(default="default"),
            preserve_default=False,
        ),
    ]
