# Generated by Django 4.2 on 2023-05-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_account_instance"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_id",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("account_id", "instance")},
        ),
    ]
