# Generated by Django 4.2 on 2023-05-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_account_account_id_alter_account_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountlookup",
            name="language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("rust", "Rust"),
                    ("ruby", "Ruby"),
                    ("java", "Java"),
                    ("csharp", "C#"),
                    ("kotlin", "Kotlin"),
                    ("fsharp", "F#"),
                    ("scala", "Scala"),
                    ("golang", "Golang"),
                    ("php", "PHP"),
                    ("linux", "Linux"),
                    ("haskell", "Haskell"),
                    ("nix", "Nix"),
                    ("opensource", "Open Source"),
                ],
                max_length=55,
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["noindex", "discoverable"],
                name="accounts_ac_noindex_0ecffa_idx",
            ),
        ),
    ]
