# Generated by Django 4.2.7 on 2023-11-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_accountlookup_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountlookup",
            name="language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("rust", "Rust"),
                    ("ruby", "Ruby"),
                    ("golang", "Golang"),
                    ("java", "Java"),
                    ("kotlin", "Kotlin"),
                    ("scala", "Scala"),
                    ("swift", "Swift"),
                    ("csharp", "C#"),
                    ("fsharp", "F#"),
                    ("cpp", "C++"),
                    ("php", "PHP"),
                    ("haskell", "Haskell"),
                    ("ocaml", "OCaml"),
                    ("nix", "Nix"),
                ],
                max_length=55,
            ),
        ),
    ]
