# Generated by Django 5.0.4 on 2024-05-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_alter_accountlookup_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="moved",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
