# Generated by Django 5.0.4 on 2024-05-18 08:54

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_account_moved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="moved",
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name="accountlookup",
            name="language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("typescript", "TypeScript"),
                    ("javascript", "JavaScript"),
                    ("rust", "Rust"),
                    ("ruby", "Ruby"),
                    ("golang", "Golang"),
                    ("java", "Java"),
                    ("kotlin", "Kotlin"),
                    ("scala", "Scala"),
                    ("swift", "Swift"),
                    ("r", "R"),
                    ("csharp", "C#"),
                    ("fsharp", "F#"),
                    ("cpp", "C++"),
                    ("css", "CSS"),
                    ("php", "PHP"),
                    ("haskell", "Haskell"),
                    ("ocaml", "OCaml"),
                    ("nix", "Nix"),
                    ("julia", "Julia"),
                ],
                max_length=55,
            ),
        ),
    ]
