# Generated by Django 5.1b1 on 2024-07-20 09:35

import django.utils.timezone
from django.db import migrations, models


def update(apps, _):
    AccountLookup = apps.get_model("accounts", "AccountLookup")
    AccountLookup.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_alter_accountlookup_language"),
    ]

    operations = [
        migrations.RunPython(
            update,
            reverse_code=lambda _, __: None,
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="statuses_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="text",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="followers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="following_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="last_status_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="daily_followers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="daily_following_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="daily_statuses_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="weekly_followers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="weekly_following_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="weekly_statuses_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="monthly_followers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="monthly_following_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accountlookup",
            name="monthly_statuses_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="accountlookup",
            name="language",
            field=models.TextField(default=""),
        ),
    ]
