# Generated by Django 5.1b1 on 2024-07-20 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_accountlookup_daily_followers_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountlookup",
            name="account",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="accounts.account"),
        ),
    ]
