# Generated by Django 5.1rc1 on 2024-08-05 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_alter_accountlookup_account"),
    ]
    operations = [
        migrations.CreateModel(
            name="Instance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instance", models.TextField(unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain", models.TextField()),
                ("title", models.TextField()),
                ("version", models.TextField()),
                ("source_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField()),
                ("usage", models.JSONField(blank=True, null=True)),
                ("thumbnail", models.JSONField()),
                ("languages", models.JSONField()),
                ("configuration", models.JSONField()),
                ("registrations", models.JSONField()),
                ("contact", models.JSONField(blank=True, null=True)),
                ("rules", models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="instance_model",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="accounts.instance"
            ),
        ),
    ]
