# Generated by Django 5.1rc1 on 2024-08-06 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_instance_account_instance_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
