# Generated by Django 5.1rc1 on 2024-08-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_instance_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountlookup",
            name="account_type",
            field=models.CharField(
                choices=[("H", "Human"), ("P", "Project"), ("?", "Unknown"), ("!", "Not Processed")],
                default="!",
                max_length=1,
            ),
        ),
    ]
