# Generated by Django 5.1 on 2024-08-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0026_accountlookup_follower_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
