# Generated by Django 5.1.3 on 2024-11-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_instance_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["text"], name="accounts_ac_text_4d0dfa_idx"),
        ),
    ]
