# Generated by Django 5.2.4 on 2025-08-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_account_activitypub_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="activitypub_id",
            field=models.URLField(blank=True, null=True),
        ),
    ]
