# Generated by Django 5.2.7 on 2025-10-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0033_alter_account_activitypub_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["username_at_instance"], name="accounts_ac_usernam_ecd7da_idx"),
        ),
    ]
