# Generated by Django 6.2.dev20260702010357 on 2026-07-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(help_text="The status text to post.")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("unlisted", "Unlisted"),
                            ("private", "Followers only"),
                            ("direct", "Direct"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("post_at", models.DateTimeField(help_text="When this announcement is due, in UTC.")),
                ("posted_at", models.DateTimeField(blank=True, help_text="Set when the post succeeded.", null=True)),
                (
                    "post_url",
                    models.URLField(blank=True, default="", help_text="Link to the published fediverse post."),
                ),
                ("error", models.TextField(blank=True, default="", help_text="Last posting error, if any.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [models.Index(fields=["posted_at", "post_at"], name="announcemen_posted__f51abb_idx")],
            },
        ),
    ]
