# Generated by Django 4.2.7 on 2023-11-06 14:46

from django.core import management
from django.db import migrations, models


def clear_tables(apps, _):
    Fwd50Account = apps.get_model("confs", "Fwd50Account")  # noqa: N806
    Fwd50Post = apps.get_model("confs", "Fwd50Post")  # noqa: N806
    Fwd50Account.objects.all().delete()
    Fwd50Post.objects.all().delete()


def run_stattag(*_, **__):
    management.call_command(
        "stattag",
        tags="fwd50",
        instances="mastodon.social,mstdn.ca,mastodon.sboots.ca,mastodon.me.uk,mstdn.ca,cosocial.ca",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(clear_tables),
        migrations.AddConstraint(
            model_name="fwd50account",
            constraint=models.UniqueConstraint(fields=("url",), name="unique_account_url"),
        ),
        migrations.AddConstraint(
            model_name="fwd50post",
            constraint=models.UniqueConstraint(fields=("url",), name="unique_post_url"),
        ),
        migrations.RunPython(run_stattag),
    ]
