# Generated by Django 4.2.7 on 2023-11-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0002_fwd50account_unique_account_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fwd50post",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="confs.fwd50account",
            ),
        ),
    ]
