# Generated by Django 5.0 on 2024-01-05 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0007_conference_accounts_conference_instances_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conference",
            name="min_id",
        ),
        migrations.CreateModel(
            name="MinId",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instance", models.TextField()),
                ("min_id", models.CharField(default="0", max_length=255)),
                ("conference", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="confs.conference")),
            ],
            options={
                "unique_together": {("conference", "instance")},
            },
        ),
    ]
