# Generated by Django 5.0.1 on 2024-02-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0008_remove_conference_min_id_minid"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="archived_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
