# Generated by Django 5.0.3 on 2024-03-10 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_accountlookup_language"),
        ("confs", "0009_conference_archived_date"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE confs_conference_accounts RENAME TO confs_conferenceaccount",
                    reverse_sql="ALTER TABLE confs_conferenceaccount RENAME TO confs_conference_accounts",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ConferenceAccount",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        (
                            "account",
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.account"),
                        ),
                        (
                            "conference",
                            models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="confs.conference"),
                        ),
                    ],
                    options={
                        "unique_together": {("conference", "account")},
                    },
                ),
                migrations.AlterField(
                    model_name="conference",
                    name="accounts",
                    field=models.ManyToManyField(blank=True, through="confs.ConferenceAccount", to="accounts.account"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conferenceaccount",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
