# Generated by Django 5.0.4 on 2024-05-05 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0011_conferencepost_alter_conference_posts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("icon", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ConferenceLookup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("typescript", "TypeScript"),
                            ("javascript", "JavaScript"),
                            ("rust", "Rust"),
                            ("ruby", "Ruby"),
                            ("golang", "Golang"),
                            ("java", "Java"),
                            ("kotlin", "Kotlin"),
                            ("scala", "Scala"),
                            ("swift", "Swift"),
                            ("csharp", "C#"),
                            ("fsharp", "F#"),
                            ("cpp", "C++"),
                            ("css", "CSS"),
                            ("php", "PHP"),
                            ("haskell", "Haskell"),
                            ("ocaml", "OCaml"),
                            ("nix", "Nix"),
                            ("julia", "Julia"),
                            ("django", "Django"),
                            ("flask", "Flask"),
                            ("fastapi", "FastAPI"),
                            ("rails", "Rails"),
                            ("laravel", "Laravel"),
                            ("symfony", "Symfony"),
                            ("kubernetes", "Kubernetes"),
                            ("spring", "Spring"),
                            ("htmx", "HTMX"),
                            ("react", "React"),
                            ("vue", "Vue"),
                            ("angular", "Angular"),
                            ("nextjs", "Next.js"),
                            ("svelte", "Svelte"),
                            ("tailwind", "Tailwind"),
                            ("bootstrap", "Bootstrap"),
                            ("dotnet", ".NET"),
                            ("opensource", "Open Source"),
                            ("linux", "Linux"),
                        ],
                        max_length=55,
                    ),
                ),
                ("conference", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="confs.conference")),
            ],
        ),
    ]
