# Generated by Django 5.1a1 on 2024-07-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0014_alter_conference_mastodon"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="days",
            field=models.TextField(
                default="",
                help_text="Comma seperated list of conference day names, e.g. Tutorials Day 1, Tutorials Day 2, Conference Day 1",
            ),
        ),
        migrations.AlterField(
            model_name="conference",
            name="instances",
            field=models.TextField(
                default="",
                help_text="Comma seperated list of instances, e.g. fosstodon.org, mastodon.social. Automatically computed",
            ),
        ),
        migrations.AlterField(
            model_name="conference",
            name="tags",
            field=models.TextField(default="", help_text="Comma seperated list of tags, e.g. #djangocon"),
        ),
    ]
