# Generated by Django 5.1a1 on 2024-07-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0016_alter_conference_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="day_style",
            field=models.TextField(
                default="",
                help_text="Comma seperated list of style names for each day, e.g. yellow, yellow, red, red, green, green",
            ),
        ),
    ]
