# Generated by Django 5.1a1 on 2024-07-10 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0017_conference_day_style"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conference",
            old_name="day_style",
            new_name="day_styles",
        ),
    ]
