# Generated by Django 5.1rc1 on 2024-08-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0018_rename_day_style_conference_day_styles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="day_styles",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma seperated list of style names for each day, e.g. yellow, yellow, red, red, green, green",
            ),
        ),
        migrations.AlterField(
            model_name="conference",
            name="days",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma seperated list of conference day names, e.g. Tutorials, Tutorials, Talks, Talks",
            ),
        ),
    ]
