# Generated by Django 5.1rc1 on 2024-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0019_alter_conference_day_styles_alter_conference_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="day_styles",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comma seperated list of style names for each day, e.g. blue, blue, red, red, green, green (if not color is set the day will be purple)",
            ),
        ),
    ]
