# Generated by Django 6.2.dev20260702010357 on 2026-07-04 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0001_initial"),
        ("confs", "0026_alter_conference_time_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="end_announcement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="announcements.announcement",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="start_announcement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="announcements.announcement",
            ),
        ),
    ]
