# Generated by Django 6.2.dev20260704023456 on 2026-07-04 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0027_conference_end_announcement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when a staff member approves the conference. Null means pending review.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who submitted this conference. Null for spreadsheet-imported rows.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_conferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
