# Generated by Django 6.2.dev20260704023456 on 2026-07-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0029_approve_existing_conferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="conference_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Icons shown for this conference in the conference list.",
                related_name="conferences",
                to="confs.conferencetag",
            ),
        ),
        migrations.AlterField(
            model_name="conferencetag",
            name="icon",
            field=models.CharField(
                help_text="Static path (e.g. languages/python.png) or a full image URL.", max_length=255
            ),
        ),
    ]
