# Generated by Django 6.2.dev20260707000319 on 2026-07-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0031_seed_conference_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="og_image",
            field=models.ImageField(blank=True, default="", upload_to="conference_og"),
        ),
        migrations.AddField(
            model_name="conference",
            name="og_image_needs_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conference",
            name="og_image_signature",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="conference",
            name="og_image_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
