# Generated by Django 6.2.dev20260820080108 on 2026-08-20 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("confs", "0033_remove_legacy_conference_tables"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Autodetector output (makemigrations confs). Applied to migration
            # state only: production unique_together values are unique indexes
            # named idx_NNNN_... (MySQL import), and AlterUniqueTogether issues
            # DROP CONSTRAINT, which raises UndefinedObject for those names.
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="djangoconafricaaccount",
                    unique_together=None,
                ),
                migrations.RemoveIndex(
                    model_name="djangoconafricaaccount",
                    name="confs_djang_noindex_e2231b_idx",
                ),
                migrations.RemoveConstraint(
                    model_name="djangoconafricaaccount",
                    name="unique_djangoconafrica_url",
                ),
                migrations.AlterUniqueTogether(
                    name="djangoconafricapost",
                    unique_together=None,
                ),
                migrations.RemoveConstraint(
                    model_name="djangoconafricapost",
                    name="unique_post_djangoconafrica_url",
                ),
                migrations.AlterUniqueTogether(
                    name="dotnetconfaccount",
                    unique_together=None,
                ),
                migrations.RemoveIndex(
                    model_name="dotnetconfaccount",
                    name="confs_dotne_noindex_cf758a_idx",
                ),
                migrations.RemoveConstraint(
                    model_name="dotnetconfaccount",
                    name="unique_dotnetcon_url",
                ),
                migrations.AlterUniqueTogether(
                    name="dotnetconfpost",
                    unique_together=None,
                ),
                migrations.RemoveConstraint(
                    model_name="dotnetconfpost",
                    name="unique_post_dotnetcon_url",
                ),
                migrations.AlterUniqueTogether(
                    name="fwd50account",
                    unique_together=None,
                ),
                migrations.RemoveIndex(
                    model_name="fwd50account",
                    name="confs_fwd50_noindex_8293c0_idx",
                ),
                migrations.RemoveConstraint(
                    model_name="fwd50account",
                    name="unique_account_url",
                ),
                migrations.AlterUniqueTogether(
                    name="fwd50post",
                    unique_together=None,
                ),
                migrations.RemoveConstraint(
                    model_name="fwd50post",
                    name="unique_post_url",
                ),
                migrations.RemoveField(
                    model_name="djangoconafricapost",
                    name="account",
                ),
                migrations.RemoveField(
                    model_name="dotnetconfpost",
                    name="account",
                ),
                migrations.RemoveField(
                    model_name="fwd50post",
                    name="account",
                ),
                migrations.DeleteModel(
                    name="DjangoConAfricaAccount",
                ),
                migrations.DeleteModel(
                    name="DjangoConAfricaPost",
                ),
                migrations.DeleteModel(
                    name="DotNetConfAccount",
                ),
                migrations.DeleteModel(
                    name="DotNetConfPost",
                ),
                migrations.DeleteModel(
                    name="Fwd50Account",
                ),
                migrations.DeleteModel(
                    name="Fwd50Post",
                ),
            ],
            database_operations=[
                migrations.DeleteModel(name="DjangoConAfricaPost"),
                migrations.DeleteModel(name="DotNetConfPost"),
                migrations.DeleteModel(name="Fwd50Post"),
                migrations.DeleteModel(name="DjangoConAfricaAccount"),
                migrations.DeleteModel(name="DotNetConfAccount"),
                migrations.DeleteModel(name="Fwd50Account"),
            ],
        ),
    ]
