# Generated by Django 5.1.3 on 2024-11-23 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_instance_deleted_at"),
        ("starter_packs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StarterPackAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.account")),
                (
                    "starter_pack",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="starter_packs.starterpack"),
                ),
            ],
            options={
                "unique_together": {("starter_pack", "account")},
            },
        ),
    ]
