# Generated by Django 5.1.3 on 2024-11-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("starter_packs", "0002_starterpackaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="starterpack",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
