# Generated by Django 5.1.4 on 2025-01-05 23:43

from django.db import migrations, models


def set_published_at(apps, _):
    StarterPack = apps.get_model("starter_packs", "StarterPack")
    # Set published_at to created_at but only for starter packs that have 1 or more account associated
    StarterPack.objects.filter(starterpackaccount__isnull=False).update(published_at=models.F("created_at"))


class Migration(migrations.Migration):
    dependencies = [
        ("starter_packs", "0003_starterpack_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="starterpack",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(set_published_at, reverse_code=migrations.RunPython.noop),
    ]
