# Generated by Django 5.1.7 on 2025-03-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("starter_packs", "0005_starterpackaccount_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="starterpack",
            name="daily_follows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="starterpack",
            name="monthly_follows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="starterpack",
            name="weekly_follows",
            field=models.IntegerField(default=0),
        ),
    ]
