# Generated by Django 5.2.4 on 2025-08-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("starter_packs", "0006_starterpack_daily_follows_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="starterpack",
            name="splash_image",
            field=models.ImageField(blank=True, default="", upload_to="splash"),
        ),
    ]
