# Generated by Django 5.2.4 on 2025-08-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("starter_packs", "0007_starterpack_splash_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="starterpack",
            name="splash_image_needs_update",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="starterpack",
            name="splash_image_signature",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="starterpack",
            name="splash_image_updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
