# Generated by Django 5.2.7 on 2025-10-11 08:43

from django.db import migrations, models
from django.db.models import Count, Q


def update_num_accounts(apps, _):
    StarterPack = apps.get_model("starter_packs", "StarterPack")

    starter_packs = (
        StarterPack.objects.filter(published_at__isnull=False, deleted_at__isnull=True)
        .annotate(
            num_accounts_computed=Count(
                "starterpackaccount__id",
                filter=Q(starterpackaccount__account__discoverable=True),
            )
        )
        .all()
    )

    for sp in starter_packs:
        sp.num_accounts = sp.num_accounts_computed

    StarterPack.objects.bulk_update(starter_packs, ["num_accounts"])


class Migration(migrations.Migration):
    dependencies = [
        ("starter_packs", "0008_starterpack_splash_image_needs_update_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="starterpack",
            name="num_accounts",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(update_num_accounts, reverse_code=migrations.RunPython.noop),
    ]
