# Generated by Django 6.1.dev20260624151946 on 2026-06-24 22:36

from django.conf import settings
from django.db import migrations, models


def seed_owners_from_created_by(apps, _schema_editor):
    """Every existing pack's original creator becomes its first owner."""
    StarterPack = apps.get_model("starter_packs", "StarterPack")
    through = StarterPack.owners.through
    rows = [
        through(starterpack_id=pack_id, user_id=created_by_id)
        for pack_id, created_by_id in StarterPack.objects.values_list("id", "created_by_id")
    ]
    through.objects.bulk_create(rows, ignore_conflicts=True, batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("starter_packs", "0009_starterpack_num_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="starterpack",
            name="owners",
            field=models.ManyToManyField(related_name="owned_starter_packs", to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(seed_owners_from_created_by, migrations.RunPython.noop),
    ]
