# Generated by Django 6.2.dev20260702010357 on 2026-07-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("starter_packs", "0011_starterpackinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="starterpackaccount",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
