# Generated by Django 6.2.dev20260707001506 on 2026-07-08 09:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("starter_packs", "0012_starterpackaccount_pinned"),
    ]

    operations = [
        migrations.AddField(
            model_name="starterpack",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ar", "Arabic"),
                        ("bn", "Bengali"),
                        ("zh-hans", "Chinese (Simplified)"),
                        ("zh-hant", "Chinese (Traditional)"),
                        ("cs", "Czech"),
                        ("da", "Danish"),
                        ("nl", "Dutch"),
                        ("en", "English"),
                        ("fi", "Finnish"),
                        ("fr", "French"),
                        ("de", "German"),
                        ("el", "Greek"),
                        ("he", "Hebrew"),
                        ("hi", "Hindi"),
                        ("hu", "Hungarian"),
                        ("id", "Indonesian"),
                        ("it", "Italian"),
                        ("ja", "Japanese"),
                        ("ko", "Korean"),
                        ("nb", "Norwegian"),
                        ("fa", "Persian"),
                        ("pl", "Polish"),
                        ("pt", "Portuguese"),
                        ("pt-br", "Portuguese (Brazil)"),
                        ("ro", "Romanian"),
                        ("ru", "Russian"),
                        ("sl", "Slovenian"),
                        ("es", "Spanish"),
                        ("sv", "Swedish"),
                        ("th", "Thai"),
                        ("tr", "Turkish"),
                        ("uk", "Ukrainian"),
                        ("vi", "Vietnamese"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
            ),
        ),
    ]
