# Generated by Django 6.2.dev20260708093209 on 2026-07-08 09:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("starter_packs", "0013_starterpack_languages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="starterpack",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32), blank=True, default=list
            ),
        ),
    ]
