name: Upgrade dependencies

on:
  schedule:
  - cron: "0 6 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
      with:
        version: "latest"
    - name: Upgrade dependencies
      run: |
        printf "### Upgraded dependencies\n\n\`\`\`\n" > update.log
        uv lock --upgrade 2>&1 | tee -a update.log
        printf "\`\`\`" >> update.log
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
      with:
        token: ${{ secrets.PAT }}
        commit-message: Upgrade dependencies
        branch: bot/upgrade-dependencies
        delete-branch: true
        title: 'Upgrade dependencies'
        body-path: update.log
